### ISSUE TITLE
Carbine first and third attack don't work

### ISSUE THREAD

**Issue by slammaja** [cleannrooster/cleannarsenal-1.20.1#1]
Hi,

I don't know since when, but first and third attack of Combustion Carbine stopped working. It seems as if the attacks stop locking the target. I am using rpgmana mod, but everything's been working fine until recently. The only thing I have updated is spell engine.

cleannarsenal v. 1.0.12.
fabric v. 0.16.5

**Comment by cleannrooster** [comment]
Should be fixed in the newest version
